version-template: $MAJOR.$MINOR.$PATCH
name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION

categories:
  - title: Features
    labels:
      - feature
      - enhancement
      - source
      - apps
      - utils
  - title: Bug Fixes
    labels:
      - patch
      - bug
      - bugfix
      - hotfix
      - fix
  - title: Maintenance
    labels:
      - build
      - documentation
      - refactoring

change-title-escapes: \<*_&

version-resolver:
  major:
    labels:
      - major
      - refactoring
  minor:
    labels:
      - feature
      - minor
      - source
      - apps
      - utils
  patch:
    labels:
      - build
      - documentation
      - patch
      - bug
      - bugfix
      - hotfix
      - fix
  default: patch

template: |
  # What’s changed

  $CHANGES
