name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install_ubuntu_18:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: sudo ./install.sh root

  install_ubuntu_20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: sudo ./install.sh root